name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: obd2-logger

      - name: Initialize
        working-directory: obd2-logger
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build firmware
        working-directory: obd2-logger
        run: |
          west build -b mimxrt1060_evk app

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: obd2-logger/build/zephyr/zephyr.*
